services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
      - DATABASE_HOST=db
      - DATABASE_PORT
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_DB
      - DATABASE_INIT_SEED
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
